name: smart_farming_pro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization & State Management
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.0.5
  shared_preferences: ^2.3.0

  # Camera & AI features
  camera: ^0.11.2
  flutter_tts: ^4.2.3
  permission_handler: ^12.0.1

  # Storage & database
  path_provider: ^2.0.15
  sqflite: ^2.2.0+4

  # Location, HTTP calls & carousel
  geolocator: ^14.0.2
  http: ^1.1.0
  carousel_slider: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true  # Required for Flutter localization code-gen

  # Assets (uncomment and add your files later)
  # assets:
  #   - assets/images/
  #   - assets/translations/
