name: my_flutter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Shared preferences
  shared_preferences: ^2.2.3

  # State management
  provider: ^6.0.5

  # Camera & AI features
  camera: ^0.10.0+4
  flutter_tts: ^3.5.0
  permission_handler: ^11.3.1

  # Storage & database
  path_provider: ^2.0.15
  sqflite: ^2.2.0+4

  # Location, HTTP calls & carousel
  geolocator: ^9.0.2
  http: ^1.1.0
  carousel_slider: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # If you want to use custom images/files later:
  # assets:
  #   - assets/images/
  #   - assets/translations/
